// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SDyUOZARvq78x7VUUgzk-pCcjh_TBnU',
    appId: '1:1000868680262:web:11deceed7d2e5bac1cf047',
    messagingSenderId: '1000868680262',
    projectId: 'budgeting-app-ai-enhanced',
    authDomain: 'budgeting-app-ai-enhanced.firebaseapp.com',
    storageBucket: 'budgeting-app-ai-enhanced.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNSYr1jv0aWUOpjua6yqF6K4cnBpAzZ4',
    appId: '1:1000868680262:android:af2ca91c7a8506dd1cf047',
    messagingSenderId: '1000868680262',
    projectId: 'budgeting-app-ai-enhanced',
    storageBucket: 'budgeting-app-ai-enhanced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqG6p53Sb0n7ILSjRkMhcragfDVMh0rw',
    appId: '1:1000868680262:ios:f05a2a075eccd6511cf047',
    messagingSenderId: '1000868680262',
    projectId: 'budgeting-app-ai-enhanced',
    storageBucket: 'budgeting-app-ai-enhanced.firebasestorage.app',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqG6p53Sb0n7ILSjRkMhcragfDVMh0rw',
    appId: '1:1000868680262:ios:f05a2a075eccd6511cf047',
    messagingSenderId: '1000868680262',
    projectId: 'budgeting-app-ai-enhanced',
    storageBucket: 'budgeting-app-ai-enhanced.firebasestorage.app',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2SDyUOZARvq78x7VUUgzk-pCcjh_TBnU',
    appId: '1:1000868680262:web:88aa3dab882efbaa1cf047',
    messagingSenderId: '1000868680262',
    projectId: 'budgeting-app-ai-enhanced',
    authDomain: 'budgeting-app-ai-enhanced.firebaseapp.com',
    storageBucket: 'budgeting-app-ai-enhanced.firebasestorage.app',
  );
}
